### ISSUE TITLE
Broken Compendium Menu

### ISSUE THREAD

**Issue by sddfsfds** [Cpt-Hazama/Persona-Mod#4]
I dont really know what to say here, i tried reloading it many times and i dont even know how it broke because it worked perfectly fine for a short bit
![20240313232738_1](https://github.com/Cpt-Hazama/Persona-Mod/assets/60235836/4eefb3b5-9d17-47f2-9d0f-0b022ec4c159)
if needed i can get the console logs when its attempted to open

**Comment by Cpt-Hazama** [comment]
Unfortunately, because the mod is undergoing a remake atm, no updates will be made to this repo

Sorry for the inconvenience
